name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - name: Generate manifest
        run: npm run prepare:hardhat

      - name: Generate types
        run: npx graph codegen

      - name: Build
        run: npx graph build

      - name: Format check
        run: npm run format:check

      - name: Test
        run: npm test
